name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0
      - run: bun install
      - run: bun lint
      - run: bun fmt
      - run: bun test
      - run: bun generateGuide human warrior
      - run: bun generateAll
